# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Города',
                'verbose_name': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название сайта для поиска')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Сайты',
                'verbose_name': 'Сайт',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Специальность')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Специальности',
                'verbose_name': 'Специальность',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(max_length=250, verbose_name='url')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.City', verbose_name='Город')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Site', verbose_name='Название сайта для поиска')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Specialty', verbose_name='Специальность')),
            ],
            options={
                'ordering': ['specialty', 'city'],
                'verbose_name_plural': 'Адреса для поиска',
                'verbose_name': 'Адрес для поиска',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок вакансии')),
                ('url', models.CharField(max_length=250, verbose_name='Интернет адрес вакансии')),
                ('description', models.TextField(blank=True, verbose_name='Описание вакансии')),
                ('company', models.CharField(blank=True, max_length=250, verbose_name='Вакансия от компании')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.City', verbose_name='Город')),
                ('site', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.Site', verbose_name='Сайт с размещением вакансии')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Specialty', verbose_name='Специальность')),
            ],
            options={
                'ordering': ['-timestamp', 'title'],
                'verbose_name_plural': 'Вакансии',
                'verbose_name': 'Вакансия',
            },
        ),
    ]
