# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_remove_vacancy_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.CharField(default=None, max_length=250, unique=True, verbose_name='Интернет адрес вакансии'),
        ),
    ]
