# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-10 08:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20180412_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ошибки скрапинга',
                'verbose_name': 'Ошибка',
                'ordering': ['-timestamp'],
            },
        ),
    ]
