# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имэйл'),
        ),
    ]
